# Generated by Django 5.0 on 2023-12-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor', models.TextField()),
                ('schoolnamegrade', models.TextField()),
                ('sig', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.TextField()),
                ('credentials', models.TextField()),
                ('identified', models.TextField()),
                ('problemface', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('note_title', models.TextField()),
                ('note_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('name1', models.TextField()),
                ('name2', models.TextField()),
                ('name3', models.TextField()),
                ('name4', models.TextField()),
                ('age1', models.TextField()),
                ('age2', models.TextField()),
                ('age3', models.TextField()),
                ('age4', models.TextField()),
                ('comment1', models.TextField()),
                ('comment2', models.TextField()),
                ('comment3', models.TextField()),
                ('comment4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='recordOfInvention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('name_of_invention', models.TextField()),
                ('problem_it_solves', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stepEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('nameinvention', models.TextField()),
                ('benefits', models.TextField()),
                ('price', models.TextField()),
                ('buy', models.TextField()),
                ('customer_age', models.TextField()),
                ('customer_gender', models.TextField()),
                ('customer_education', models.TextField()),
                ('customer_house', models.TextField()),
                ('customer_marital', models.TextField()),
                ('other_notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stepFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('materials', models.TextField()),
                ('findings', models.TextField()),
                ('credit', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stepOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('identify_problems', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stepSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('testing', models.TextField()),
                ('positive', models.TextField()),
                ('negative', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='stepSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('prototype_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='stepThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('factors', models.TextField()),
                ('ways_to_solve', models.TextField()),
                ('research', models.TextField()),
                ('difference', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='surveyLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('things_enjoyed', models.TextField()),
                ('thanking', models.TextField()),
                ('difficulty', models.TextField()),
                ('future', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='statementOfOriginality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('inventors', models.ManyToManyField(related_name='statement_of_originality', to='web.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='stepFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ImageField(blank=True, null=True, upload_to='')),
                ('teacher_name', models.TextField()),
                ('teacher_sign', models.TextField()),
                ('date', models.TextField()),
                ('sol_design_problem', models.TextField()),
                ('green_sol', models.TextField()),
                ('issues', models.ManyToManyField(related_name='step_four', to='web.issue')),
            ],
        ),
        migrations.CreateModel(
            name='stepTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('problem_title', models.TextField()),
                ('problem_description', models.TextField()),
                ('describe_problem', models.TextField()),
                ('specific_solution', models.TextField()),
                ('problems', models.ManyToManyField(related_name='step_two', to='web.problem')),
            ],
        ),
    ]
