# Generated by Django 5.0 on 2024-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepfour',
            name='blueprint',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
